### ISSUE TITLE
Re-export `filter::Filter` to top-level

### ISSUE THREAD

**Issue by TheNeikos** [matthiasbeyer/filters#2]
This is really a simple thing, you go and put this line to the lib.rs:

``` rust
pub use filter::Filter;
```

I will happily do this tomorrow

**Comment by matthiasbeyer** [comment]
"Tomorrow" didn't happen yet, did it? :smile:

**Comment by matthiasbeyer** [comment]
I don't know what you're planning here,... I'm not sure why we should export the `Filter` trait to the top level, actually. May I close this issue?

**Comment by TheNeikos** [comment]
So you have less to type?

**Comment by matthiasbeyer** [comment]
So you mean

```rust
use filters::filter::Filter;
```

vs.

```rust
use filters::Filter
```

?
