### ISSUE TITLE
Implement `BitAnd`, `BitOr`, `BitXor` and `Not` for all implementations of `Filter<N>`

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/filters#4]
This is a really hard issue, IMHO.

Basically, we want to be able to rewrite this:

``` rust
let a = |&a: &usize| *a == 1;
let b = |&b: &usize| *a > 10;

let c = a.and(b);
```

as 

``` rust
let a = |&a: &usize| *a == 1;
let b = |&b: &usize| *a > 10;

let c = a & b;
```

so basically, we want to implement `BitAnd`, `BitOr`, `BitXor` and `Not` from `std::ops`.

**Comment by Emerentius** [comment]
̀This, just like #5, is not possible for the general case of `impl<N, T: Filter<N>> BitAnd for T {}`. Reason being that `BitAnd` and co are not your own traits and can therefore not be implemented for structs that you don't define yourself.
Defining them for `And`, `Or` etc should be quite simple though.

**Comment by matthiasbeyer** [comment]
@Emerentius Do you think we could add intermediate types and cover it by implementing `BitAnd` and others on them?

Something like (pseudorust)

```rust
impl Into<BitAndFilter> for F where F: Filter { /* I guess it wouldn't work because of this line, right? */
    /*...*/
}

impl BitAnd for BitAndFilter {
    /*...*/
}
```

And if yes, would it work to

```rust
let a  = |&a: &usize| *a == 1;
let b  = |&b: &usize| *b == 7;

a & b /* would this work, aka. would the compiler automatically call into() on both variables?
```

---

Defining them on `And`, `Or`, etc would work, yes. This way we would still need to call `and` and `or` for chaining predicates.

---

Another idea: Could we implement a macro, that one can call for custom types that implement `Filter`? Something like this:


```rust
use filters::filter::Filter;
struct EqTo { pub i: usize }

impl Filter<usize> for EqTo {
    fn filter(&self, n: &usize) -> bool { self.i == *n }
}

impl_and_op_filter(EqTo);
impl_or_op_filter(EqTo);
impl_not_op_filter(EqTo);
/* 
    and maybe even a "super"-macro that implements all of them:
    impl_operators_on_filter(EqTo);
*/
```

which then implements the `BitAnd`, `BitOr` and `BitNot` traits for the `EqTo` type? This way we could still have operators for filters, though the user would need to call these macros explicitely. 

I'd prefer a solution where the user does not need to do extra things besides implementing `Filter`, though if there is no other way we could provide these macros.

**Comment by Emerentius** [comment]
Automatic conversions of the left-hand side are not possible except via `Deref` and we neither can nor should implement that.
Macros as custom derive implementation should be possible.

**Comment by matthiasbeyer** [comment]
I guess that's the way then.

**Comment by Emerentius** [comment]
You can actually

**Comment by Emerentius** [comment]
You can actually

**Comment by matthiasbeyer** [comment]
So `pub trait BitAnd<RHS = Self>` just says that the RHS has to implement `BitAnd` as well?

**Comment by PlasmaPower** [comment]
This should be implemented like #8, with a macro for all structs.

However, now that I think about it, this will be an even bigger problem as it will be needed as a macro for any two combinations of structs, not just one for every struct. That might not be possible.

**Comment by Emerentius** [comment]
`RHS = Self` is just a default type. It means you can implement it like `impl BitAnd for MyType` and it will be equivalent to `impl BitAnd<MyType> for MyType`

I ran into quite the genericity problem with this.

My first attempt was to simply implement it like this:
```
use std::ops::BitAnd;
impl<I, RHS, T, U> BitAnd<RHS> for And<T, U>
    where RHS: Filter<I>,
          T: Filter<I>,
          U: Filter<I>,
{
    type Output = And<Self, RHS>;

    fn bitand(self, other: RHS) -> Self::Output {
        And::new(self, other)
    }
}
```

That is not allowed however as the type `I` is not constrained by anything. `I` has to be used as either a parameter of the trait, the type I'm implementing the trait for or any of their associated types. Reason for this is, because `Filter<I>` is a generic trait, a type could implement however many implementations it wants. `T` could be both `Filter<&u32>` as well as `Filter<&[bool]>`. No limits. In that case rustc wouldn't know which to choose.

So next I tried making `Filter` non-generic and making the input type an associated type like so:
```
pub trait Filter {
    type Input;

    /// The function which is used to filter something
    fn filter(&self, &Self::Input) -> bool;
    /* everything else */
}
```

Now this works:
```
use std::ops::BitAnd;
impl<I, RHS, T, U> BitAnd<RHS> for And<T, U>
    where RHS: Filter<Input=I>,
          T: Filter<Input=I>,
          U: Filter<Input=I>,
{
    type Output = And<Self, RHS>;

    fn bitand(self, other: RHS) -> Self::Output {
        And::new(self, other)
    }
}
```

However, the blanket implementation of Filter for closures becomes impossible now. For the exact same reason that the previous approach failed.
```
/// All closures that take a ref to something and return bool are filters
impl<I, T: Fn(&I) -> bool> Filter for T {
    type Input = I;

    fn filter(&self, other: &I) -> bool {
        self(other)
    }
}
```

A type T can implement `Fn` for however many types `&I` it wants.

**Comment by PlasmaPower** [comment]
@Emerentius Yeah I ran into that same problem. Interesting.

**Comment by TheNeikos** [comment]
@Emerentius 
In Rust Traits generally take Inputs as Generics and Outputs as Associated Types.

I ran into that trouble while _implementing_ the library, and this way was the only one that worked and actually made sense from a history point of view.

**Comment by Emerentius** [comment]
If the type is locked into a certain argument type like so:
```
pub struct And<T: Filter<I>, U: Filter<I>, I> {
    a: T,
    b: U,
    input: PhantomData<I>,
}
```

This now becomes possible:
```
use std::ops::BitAnd;
impl<I, RHS, T, U> BitAnd<RHS> for And<T, U, I>
    where RHS: Filter<I>,
          T: Filter<I>,
          U: Filter<I>,
{
    type Output = And<Self, RHS, I>;

    fn bitand(self, other: RHS) -> Self::Output {
        And::new(self, other)
    }
}
```

But type inference is a bitch. The following works, but leave out a type in any of the closures and it fails to compile.
```
let and = And::new(|&x: &usize| x > 10, |&x: &usize| x < 100);
let and_ = and & |&x: &usize| x % 2 == 0;
(0..10usize).filter(|x| and_.filter(x));
```

**Comment by TheNeikos** [comment]
Interesting, the latter restriction doesn't change anything from the status quo does it?

**Comment by Emerentius** [comment]
No restrictions when you use closures because those only implement `Fn*` for a single input type anyway. However, if you were to create your own struct and implement `Fn*` for multiple different input types `And` and co could propagate that genericity without the marker. With the marker you have to decide upon one input type when creating an instance of `And`.

**Comment by matthiasbeyer** [comment]
Another idea:

I guess I would be okay if someone could implement a macro for this.

I think of something like this (names are shallow):

```rust
let filter_a = /* some closure */
let filter_b = /* some closure */
let filter_c = /* some closure */

let filter = construct_filters! { (filter_a and filter_b) or filter_c };

// or, same output:
let filter = construct_filters! { (filter_a && filter_b) || filter_c };

// and maybe (other output):
let filter = construct_filters! { (filter_a -> filter_b) <-> filter_c };
```

We might even support both the `and` and the `&&` notation... I'm not sure about whether `->` operators  would be nice.

We might even support another macro `filter_algebra!()` which gives us the possibility to use [boolean algebra](https://en.wikipedia.org/wiki/Boolean_algebra) when constructing filters (we could use `^` for `and` and `v` for `or`... `!` would still be `not`).

**Comment by matthiasbeyer** [comment]
Closing as development is moved to sourcehut.
