### ISSUE TITLE
We want to be able to use an implementation of `Filter<N>` as function.

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/filters#5]
By now we do 

```
let a = |&a: &usize| *a == 1;
let b = |&b: &usize| *a == 2;
let c = a.or(b);

myvec.iter().filter(|x| c.filter(x))
```

but it would be way cooler to do

```
let a = |&a: &usize| *a == 1;
let b = |&b: &usize| *a == 2;
let c = a.or(b);

myvec.iter().filter(c) # Filter::filter() gets called automatically
```

I'm not sure how to approach this, but it would be nice to have.

**Comment by PlasmaPower** [comment]
You'll have to implement [`std::ops::Fn`](https://doc.rust-lang.org/std/ops/trait.Fn.html), but the API for that is unstable as the current `args` argument has problems (and will likely be replaced with variadic arguments). See https://github.com/rust-lang/rust/issues/29625.

**Comment by PlasmaPower** [comment]
I'm working on a PR for this as an optional feature now.
