### ISSUE TITLE
Relicense?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/filters#9]
Hi,

I thought about the issue with the license (documented in [this reddit](https://www.reddit.com/r/rust/comments/4xd195/ann_filters_a_library_to_build_predicates_and/d6efxz2))

We would relicense with MIT and Apache2 - as suggested. I'm just generally asking if everyone is okay with it, I will then ask @cmr to send one of his famous relicensing-PRs (as you can [see here](https://github.com/nathan7/libfringe/pull/26)).

So, are you guys okay with relicensing and if not - why?

@TheNeikos
@PlasmaPower 
@Emerentius

**Comment by Emerentius** [comment]
I prefer user freedom preserving licences but I'll agree to whatever license you choose.
I don't think that little amount of work I did is worth fuzzing about.

**Comment by PlasmaPower** [comment]
Looking at the linked discussion on Reddit, I think we should definitely switch licenses. I'm okay with both MIT and Apache2.

@Emerentius have you looked at the discussion on Reddit? It looks like the LGPL might not be a practical option for Rust programs.

**Comment by TheNeikos** [comment]
I would agree with the MPL, I do not think MIT/Apache2 is a healthy mix.

**Comment by PlasmaPower** [comment]
MPL sounds like a better idea. From my understanding it's similar to the GPL but relaxes rules on linking.

**Comment by TheNeikos** [comment]
@PlasmaPower Yes

---

For the record: https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by matthiasbeyer** [comment]
@PlasmaPower , @TheNeikos yes, and as described in the linked reddit thread, MIT is for linking with GPL'ed software, as MPL does not allow this... (as far as I understand things).

**Comment by TheNeikos** [comment]
From the FAQ:

Q11:
> This allows, for example, programs using MPL-licensed code to be statically linked to and distributed as part of a larger proprietary piece of software, which would not generally be possible under the terms of stronger copyleft licenses

**Comment by matthiasbeyer** [comment]
MPL sounds nice, yes. I will read about it now.

**Comment by Emerentius** [comment]
@PlasmaPower 
I have looked at the discussion. LGPL is perfectly practical but it means additional work for closed source code bases but I don't care about optimizing for non-free software.

**Comment by TheNeikos** [comment]
@Emerentius 
LGPL doesn't allow it for incompatible licenses, so MIT is out of the window too for example

**Comment by Emerentius** [comment]
Doesn't allow what?

**Comment by TheNeikos** [comment]
Linking to non-GPL source

**Comment by PlasmaPower** [comment]
I think everyone agrees on the MPL, right?

**Comment by matthiasbeyer** [comment]
Yes seems so. I will ask cmr to do one of his relicensing prs tomorrow.
